### ISSUE TITLE
Sample?

### ISSUE THREAD

**Issue by nlogozzo** [entvex/NgrokSharp#3]
Hi, 
I would like to use this library in my project ([NickvisionPromote](https://github.com/NickvisionTech/NickvisionPromote)) as it has a webserver that I would like to port forward using ngrok all from the C# ode.
Would you be able to provide a sample of how to use this library. 
Thanks!

**Comment by entvex** [comment]
Yes, i'll make a new comment here tomorrow :) and addresse the issue

**Comment by nlogozzo** [comment]
> Yes, i'll make a new comment here tomorrow :) and addresse the issue

Thank you I really appreciate it!

**Comment by entvex** [comment]
@nlogozzo I think it very cool, that you decided to give my library a chance.

If you would like to see a live example where it is used, please look [here](https://github.com/entvex/NgrokSharp) In the repo there is a file named [MainWindow.xaml.cs](https://github.com/entvex/NgrokGUI/blob/master/MainWindow.xaml.cs) there you can find code where i use the library. Sorry if the code don't make use of MVVM, but i plan to use that in a new version i am working on. NgrokGUI was put together fast to help people out. Also Look for at line [17](https://github.com/entvex/NgrokGUI/blob/27a551ceb4328e2b0a7df0ca8d5ec780f759f39a/MainWindow.xaml.cs#L17), where i create the interface and make use of it.

NgrokSharp will also help you get it ready for use, please see [FirstTimeWizard.xaml.cs](https://github.com/entvex/NgrokGUI/blob/27a551ceb4328e2b0a7df0ca8d5ec780f759f39a/FirstTimeWizard.xaml.cs#L61) where i download Ngrok and the [event](https://github.com/entvex/NgrokGUI/blob/27a551ceb4328e2b0a7df0ca8d5ec780f759f39a/FirstTimeWizard.xaml.cs#L38) to let you know the download is ready.  You can register your auth token [here](https://github.com/entvex/NgrokGUI/blob/27a551ceb4328e2b0a7df0ca8d5ec780f759f39a/FirstTimeWizard.xaml.cs#L91).

You can also see the unit tests for NgrokSharp [here](https://github.com/entvex/NgrokSharp/blob/master/NgrokSharp.Tests/NgrokManagerUnitTest.cs) where i make it do some things.

I will start making in code documentation, hopefully that will also help a bit.

Please let me know if you have some ideas or issues with NgrokSharp. 👍 
I hope it makes sense, if not feel free to ask again

**Comment by nlogozzo** [comment]
I want to make sure ngrok stays up to date. Is there a way to keep track of version downloaded and only download a new version when needed. Or do I always have to download ngrok on application startup?

**Comment by entvex** [comment]
hmm good question, it's not really a problem I have had. I just downloaded it once and then just kept using it. I think they rarely issue updates. It's something i could see, if i could find a nice and clean way to build into the API.

Did The places i pointed you to, help with using NgrokSharp ?

**Comment by nlogozzo** [comment]
> Did The places i pointed you to, help with using NgrokSharp ?

Going to try and implement my new feature now, i'll let you know how it goes

**Comment by nlogozzo** [comment]
@entvex sorry didn't have time to put my solution together before, doing it now...Just a few suggestions with C# syntax and guidelines .
Your property names, for example in `StartTunnelDTO`, should be capital. So `Name` instead of `name`. You should also spell out the properties, so `Protocol` instead of `proto`
Also methods you can `await` such as `StartTunnel` should have Async at the end of them, so `StartTunnelAsync` instead.

**Comment by nlogozzo** [comment]
So here is my code:
```csharp
if(!_downloadedNgrokThisSession)
{
    using var downloadCancellationToken = new CancellationTokenSource();
    _ngrokManager.DownloadAndUnZipDone += (sender, e) => downloadCancellationToken.Cancel();
    await Task.Run(() => _ngrokManager.DownloadNgrok());
    await Task.Run(() => WaitHandle.WaitAny(new[] { downloadCancellationToken.Token.WaitHandle }));
    _downloadedNgrokThisSession = true;
}
_ngrokManager.RegisterAuthToken(apiKey);
_ngrokManager.StartNgrok();
var tunnel = new StartTunnelDTO
{
    name = "Incomming Messages Server",
    proto = "http",
    addr = "5001"
};
var result = await _ngrokManager.StartTunnel(tunnel);
if((int)result.StatusCode == 201)
{
    var tunnelDetail = JsonSerializer.Deserialize<TunnelDetailDTO>(await result.Content.ReadAsStringAsync());
    return tunnelDetail.PublicUrl.ToString() + "/sms";
}
else
{
    var tunnelError = JsonSerializer.Deserialize<TunnelErrorDTO>(await result.Content.ReadAsStringAsync());
    throw new ApplicationException(tunnelError.Msg);
}
```
I'm trying to port forward `http://localhost:5001`. However when I run the program it downloads ngrok no problem but when it goes to start I get the error: `System.Net.Http.HttpRequestException: 'No connection could be made because the target machine actively refused it. (localhost:4040)'` 
What does that mean and how do I fix it?
This is the line throwing the error: `var result = await _ngrokManager.StartTunnel(tunnel);`

**Comment by entvex** [comment]
@nlogozzo Thanks for the feedback.

> Your property names, for example in StartTunnelDTO, should be capital. So Name instead of name

Yeah that is true, i kept it lowercase because the tunnel-definitions, made by Ngrok is lowercase. So it was easier to convert it to JSON and send it to the Ngrok endpoint.

> You should also spell out the properties, so Protocol instead of proto

I agree that proto, is confusing, it also confuses me sometimes. The reason i kept the name as proto and not Protocol. Is because the JSON I sent to Ngrok want it to be named [proto](https://ngrok.com/docs#tunnel-definitions). But this is good feedback. To make it easier to use i should rename it to Protocol and just map it to proto, before the API sends it to ngrok. That should make it easier to understand for people using the library or least document it, so people understand it.

> Also methods you can await such as StartTunnel should have Async at the end of them, so StartTunnelAsync instead.

Yes good feedback I should really rename that!
Now onto your code!

> I'm trying to port forward http://localhost:5001. However when I run the program it downloads ngrok no problem but when it goes to start I get the error: System.Net.Http.HttpRequestException: 'No connection could be made because the target machine actively refused it. (localhost:4040)'
What does that mean and how do I fix it?

Now because Ngrok, is an external program that runs as a process, it needs to start register the auth token and exit, and on some systems that takes a little while. The same happens when Ngrok starts, it can take a little time for it's web server to startup. So please try to put a few sleeps in it.

```csharp
if(!_downloadedNgrokThisSession)
{
    using var downloadCancellationToken = new CancellationTokenSource();
    _ngrokManager.DownloadAndUnZipDone += (sender, e) => downloadCancellationToken.Cancel();
    await Task.Run(() => _ngrokManager.DownloadNgrok());
    await Task.Run(() => WaitHandle.WaitAny(new[] { downloadCancellationToken.Token.WaitHandle }));
    _downloadedNgrokThisSession = true;
}
_ngrokManager.RegisterAuthToken(apiKey);
System.Threading.Thread.Sleep(1000);
_ngrokManager.StartNgrok();
System.Threading.Thread.Sleep(1000);
var tunnel = new StartTunnelDTO
{
    name = "Incomming Messages Server",
    proto = "http",
    addr = "5001"
};
var result = await _ngrokManager.StartTunnel(tunnel);
System.Threading.Thread.Sleep(1000);
if((int)result.StatusCode == 201)
{
    var tunnelDetail = JsonSerializer.Deserialize<TunnelDetailDTO>(await result.Content.ReadAsStringAsync());
    return tunnelDetail.PublicUrl.ToString() + "/sms";
}
else
{
    var tunnelError = JsonSerializer.Deserialize<TunnelErrorDTO>(await result.Content.ReadAsStringAsync());
    throw new ApplicationException(tunnelError.Msg);
}
```
There is properly too many, and the sleep is too long here, but i just want to find the issue and make it work for you first, and then when the issue is pinned down fix the API. **I don't like putting sleeps** in and so, if it works, this behavior in the API would need to be reworked so it gives a better developer experience.

On another note
I saw you made one http tunnel therefor I wanted to tell you that ngrok’s default behavior for http when no additional properties are passed is to open two tunnels, one http and one https.  If only a single https tunnel is needed, pass bind_tls=True in StartTunnelDTO

I hope this helps and if not please do not hesitate to respond to anything here :) I really wanna make the lib better.
I hope it makes sense, if not feel free to ask again

**Comment by nlogozzo** [comment]
@entvex Still the same issue.
I'm going to fork the library and rework it a little, make more things async and then we can test out that version

**Comment by nlogozzo** [comment]
I think I also found the issue. You have this `private readonly Uri _ngrokLocalUrl = new("http://localhost:4040/api");` and every time you start a tunnel you return ` return await _httpClient.PostAsync($"{_ngrokLocalUrl}/tunnels",  new StringContent(JsonConvert.SerializeObject(startTunnelDto), Encoding.UTF8, "application/json"));` which is the localhost 4040 error I was getting.
Any ideas? I'm still going to rewrite things now and we can test them

**Comment by nlogozzo** [comment]
I created this pull request: https://github.com/entvex/NgrokSharp/pull/5
I don't expect this to fix the issue were having (even tho it might) but it should definitely make the library work and run a little better. Would you be able to upload V1.0.8 to nuget so I can test it properly. You can even change the version to 1.0.8-beta and nuget will mark it as a beta

**Comment by nlogozzo** [comment]
I also would like to create another pull request as the library saves the files in the current working directory which is fine for debugging and testing applications. However, if an application is installed in the system (stored in ProgramFiles) the user will need to run the application with administrator rights to be able to save the files there. Therefore, I'm going to create another pr later today that will save the files to the user's AppData folder (in which they always have access to)
Also do you have a discord or something that would allow us to more easily communicate?

**Comment by entvex** [comment]
Dear @nlogozzo 

> I think I also found the issue. You have this `private readonly Uri _ngrokLocalUrl = new("http://localhost:4040/api");` and every time you start a tunnel you return ` return await _httpClient.PostAsync($"{_ngrokLocalUrl}/tunnels", new StringContent(JsonConvert.SerializeObject(startTunnelDto), Encoding.UTF8, "application/json"));` which is the localhost 4040 error I was getting.
> Any ideas? I'm still going to rewrite things now and we can test them

The reason that i have the http://localhost:4040/api, is because when Ngrok starts it exposes it's API as rest. So it's the way to make it, do the work.  Så if you go to [ngrok](https://ngrok.com/download) and download it and run it with 
`
.\ngrok.exe start --none
`
In the terminal. then you can vist it's dashboard on the url http://localhost:4040/inspect/http and http://localhost:4040/api is where NgrokSharp sendes it's commands to.

**Comment by nlogozzo** [comment]
> Dear @nlogozzo
> 
> > I think I also found the issue. You have this `private readonly Uri _ngrokLocalUrl = new("http://localhost:4040/api");` and every time you start a tunnel you return ` return await _httpClient.PostAsync($"{_ngrokLocalUrl}/tunnels", new StringContent(JsonConvert.SerializeObject(startTunnelDto), Encoding.UTF8, "application/json"));` which is the localhost 4040 error I was getting.
> > Any ideas? I'm still going to rewrite things now and we can test them
> 
> The reason that i have the http://localhost:4040/api, is because when Ngrok starts it exposes it's API as rest. So it's the way to make it, do the work. Så if you go to [ngrok](https://ngrok.com/download) and download it and run it with
> `.\ngrok.exe start --none`
> In the terminal. then you can vist it's dashboard on the url http://localhost:4040/inspect/http and http://localhost:4040/api is where NgrokSharp sendes it's commands to.


Ah ok makes sense.
Like I said, I urge you to look and merge the PR and release a new version on github and we can test that.

**Comment by entvex** [comment]
Dear @nlogozzo I think it is a good idea to make a discord for this project. I have been thinking about it, but i was not sure when it would be needed. But now is the time, so I'll create one tonight and invite you to it. Sorry i can't respond to all you comments right now as i have some errands to do. But I'll reply later and invite you to the official NgrokSharp discord server :).

**Comment by nlogozzo** [comment]
Ok sounds good! Look forward to communicating on the discord

**Comment by entvex** [comment]
Now there is a discord link in the readme.md 👍
